//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileExporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileExporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حسابداری بانک.
        /// </summary>
        internal static string bank_acc_key {
            get {
                return ResourceManager.GetString("bank_acc_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        internal static string bank_des {
            get {
                return ResourceManager.GetString("bank_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب بانکی.
        /// </summary>
        internal static string bank_hesab {
            get {
                return ResourceManager.GetString("bank_hesab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه بانک.
        /// </summary>
        internal static string bank_id {
            get {
                return ResourceManager.GetString("bank_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک.
        /// </summary>
        internal static string bank_name {
            get {
                return ResourceManager.GetString("bank_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام جدید بانک.
        /// </summary>
        internal static string bank_new_name {
            get {
                return ResourceManager.GetString("bank_new_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شعبه.
        /// </summary>
        internal static string bank_shobe_code {
            get {
                return ResourceManager.GetString("bank_shobe_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد محصول قدیم.
        /// </summary>
        internal static string cdcode {
            get {
                return ResourceManager.GetString("cdcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فاکتور.
        /// </summary>
        internal static string invoiceid {
            get {
                return ResourceManager.GetString("invoiceid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جایزه دار؟.
        /// </summary>
        internal static string isbonus {
            get {
                return ResourceManager.GetString("isbonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه قیمت.
        /// </summary>
        internal static string priceid {
            get {
                return ResourceManager.GetString("priceid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد محصول.
        /// </summary>
        internal static string productcode {
            get {
                return ResourceManager.GetString("productcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوای بار کد.
        /// </summary>
        internal static string qrcodecontent {
            get {
                return ResourceManager.GetString("qrcodecontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        internal static string qty {
            get {
                return ResourceManager.GetString("qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        internal static string row {
            get {
                return ResourceManager.GetString("row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        internal static string unitid {
            get {
                return ResourceManager.GetString("unitid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه واحد.
        /// </summary>
        internal static string vahed_key {
            get {
                return ResourceManager.GetString("vahed_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد انبار.
        /// </summary>
        internal static string whcode {
            get {
                return ResourceManager.GetString("whcode", resourceCulture);
            }
        }
    }
}
